main:
  hostname: domain-aaa.com
  user: rtcamp
  deploy_path: /opt/easyengine/sites/domain-aaa.com/app/htdocs

develop:
  hostname: domain-aaa.rt.gw
  user: rtcamp
  deploy_path: /opt/easyengine/sites/domain-aaa.rt.gw/app/htdocs
