on:
  push:
    branches:
      - main
      - develop

name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-deploy-wordpress@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          NODE_VERSION: 18
          NODE_BUILD_COMMAND: npm ci
